spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 367300
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true



